version: "3"
services:
  auth:
    # replace username/repo:tag with your name and image details
    image: gsowards/auth-server:latest
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "4"
          memory: 2G
      restart_policy:
        condition: on-failure
    ports:
    - "443:443"
    networks:
    - authnet
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
    - "8080:8080"
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
    - authnet
networks:
  authnet: